version: "3.7"

services:

  doa:
    image: uiobmi/localega-doa
    ports:
      - 8080:8080
    environment:
      - DB_INSTANCE
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - S3_ENDPOINT
      - S3_ACCESS_KEY
      - S3_SECRET_KEY
      - JWT_PUBLIC_KEY_PATH
      - CRYPT4GH_PRIVATE_KEY_PATH
      - CRYPT4GH_PRIVATE_KEY_PASSWORD_PATH
    secrets:
      - source: CA.cert
        target: /usr/local/share/ca-certificates/CA.cert
      - source: jwt_public_key
        target: /etc/jwt/key.pem
      - source: crypt4gh_private_key
        target: /etc/crypt4gh/key.pem

secrets:
  CA.cert:
    file: ./CA.cert
  jwt_public_key:
    file: ./jwt.pub.pem
  crypt4gh_private_key:
    file: ./key.sec
  crypt4gh_private_key_password:
    file: ./key.pass
