spring:
  datasource:
    url: jdbc:postgresql://${DB_INSTANCE:localhost}:${DB_PORT:5432}/${POSTGRES_DB:localega}?stringtype=unspecified
    username: ${POSTGRES_USER:test}
    password: ${POSTGRES_PASSWORD:test}
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

s3:
  endpoint: ${S3_ENDPOINT:localhost}
  port: ${S3_PORT:9000}
  access-key: ${S3_ACCESS_KEY:minio}
  secret-key: ${S3_SECRET_KEY:miniostorage}
  region: ${S3_REGION:us-west-1}
  secure: ${S3_SECURE:false}
  bucket: ${S3_BUCKET:localega}

jwt.public-key-path: ${JWT_PUBLIC_KEY_PATH:}

crypt4gh.private-key-path: ${CRYPT4GH_PRIVATE_KEY_PATH:}
