name: Java CI

on:
  push:

jobs:

  build:

    strategy:
      fail-fast: true

    runs-on: ubuntu-latest

    env:
      SSL_ENABLED: false
      DB_INSTANCE: localhost
      ROOT_CERT_PATH: test/rootCA.pem
      CERT_PATH: test/localhost-client.pem
      CERT_KEY: test/localhost-client-key.der
      POSTGRES_PASSWORD: password
      OPENID_CONFIGURATION_URL: http://localhost:8000/openid-configuration
      CRYPT4GH_PRIVATE_KEY_PATH: test/crypt4gh.sec.pem
      CRYPT4GH_PRIVATE_KEY_PASSWORD_PATH: test/crypt4gh.pass

    steps:

      - uses: actions/checkout@v1

      - name: Pre-configuration
        run: |
          sudo apt-get install rng-tools
          sudo rngd -r /dev/urandom
          sudo chown 70:70 test/localhost-key.pem
          sudo chmod 600 test/localhost-key.pem

      - name: Docker Compose Up
        run: docker-compose up -d

      - name: Set up JDK 13
        uses: actions/setup-java@v1
        with:
          java-version: 13

      - name: Sleep
        run: sleep 30

      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Spring Boot Run
        run: nohup mvn spring-boot:run --no-transfer-progress > nohup.out &

      - name: Waith for app to start
        run: |
          RETRY_TIMES=0
          until lsof -i -P -n | grep ":8080";
          do
          RETRY_TIMES=$((RETRY_TIMES+1));
          if [ $RETRY_TIMES -eq 30 ]; then exit 1; fi
          sleep 10;
          done

      - name: Test
        run: mvn test --no-transfer-progress

      - name: Docker Compose Logs
        if: failure()
        run: docker-compose logs

      - name: Spring Boot Run Logs
        if: failure()
        run: cat nohup.out
